#
# TOML
#
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

#
# Quickrun
#
[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'
on_ft = 'quickrun'
depends = 'vim-quickrun'

#
# Markdown
#
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = 'markdown'
build = 'cd app & yarn install'
hook_add = '''
let g:mkdp_auto_start = 0
let g:mkdp_auto_close = 0
let g:mkdp_refresh_slow = 0
let g:mkdp_command_for_global = 0
let g:mkdp_open_to_the_world = 0
let g:mkdp_open_ip = ''
let g:mkdp_browser = ''
let g:mkdp_echo_preview_url = 0
let g:mkdp_browserfunc = ''
let g:mkdp_preview_options = {
    \ 'mkit': {},
    \ 'katex': {},
    \ 'uml': {},
    \ 'maid': {},
    \ 'disable_sync_scroll': 0,
    \ 'sync_scroll_type': 'middle',
    \ 'hide_yaml_meta': 1,
    \ 'sequence_diagrams': {}
    \ }
let g:mkdp_markdown_css = ''
let g:mkdp_highlight_css = ''
let g:mkdp_port = ''
let g:mkdp_page_title = '「${name}」'
'''

[[plugins]]
on_ft = 'mermaid'
repo = 'mracos/mermaid.vim'

#
# TypeScript
#
[[plugins]]
on_ft = 'typescript'
repo = 'leafgarland/typescript-vim'

[[plugins]]
on_ft = 'typescript'
repo = 'Quramy/tsuquyomi'

#
# Elm
#
[[plugins]]
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

#
# CSS, HTML
#
[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
on_ft = ['css', 'html']
hook_add = '''
let g:user_zen_settings = {'indentation' : '  '}
'''

#
# jinja
#
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = 'jinja'

#
# SQL
#
[[plugins]]
repo = 'b4b4r07/vim-sqlfmt'
on_ft = 'sql'
hook_add = '''
let g:sqlfmt_command = "sqlfmt"
let g:sqlfmt_options = ""
let g:sqlfmt_auto = 0
'''

#
# Terraform
#
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
let g:terraform_fmt_on_save = 1
'''
